name: 'Create Markdown Table'
description: 'Generate a markdown table from a JSON or YAML file'
author: 'gazab'
inputs:
  json-file:
    description: 'path to the JSON file to create a table from'
    required: false
  yaml-file:
    description: 'path to the YAML file to create a tablef from'
    required: false
outputs:
  table:
    description: 'The table in markdown format'
runs:
  using: 'node16'
  main: 'dist/index.js'
