name: 'Create Markdown Table'
description: 'Generate a markdown table from a JSON or YAML file'
author: 'gazab'
inputs:
  file:
    description: 'path to the JSON/YAML file to create a table from'
    required: true
outputs:
  table:
    description: 'The table in markdown format'
runs:
  using: 'node16'
  main: 'dist/index.js'
