name: 'Create Markdown Table'
description: 'Generate a markdown table from a JSON or YAML file'
author: 'gazab'
branding:
  icon: 'menu'
  color: 'purple'
inputs:
  file:
    description: 'path to the JSON/YAML file to create a table from'
    required: true
  columns:
    description: 'List of columns and their order to include in the table. Use JSON format.'
    required: false
  capitalize:
    description: 'Capitalize the first letter of each column name in the header. Default: true'
    default: 'true'
    required: false
outputs:
  table:
    description: 'The table in markdown format'
runs:
  using: 'node16'
  main: 'dist/index.js'
